---
- hosts: "{{ target }}"
  remote_user: root
  roles:
    - ../roles/nginx
  tasks:

  - name: checkout latest nginx
    shell: cd /etc/nginx && sudo git pull && sudo git checkout

  - name: edit nginx.conf config
    shell: "sudo sed -i -e 's%{{ item.key }}%{{ item.value }}%g' /etc/nginx/nginx.conf"
    with_dict: "{{ replace }}"

  - name: build nginx image
    shell: sudo docker build -t "nginx" /etc/nginx

  - name: delete nginx container
    shell: sudo docker rm -f {{ container_name }}
    ignore_errors: yes

  - name: run new nginx container
    shell: (sudo docker run -d --name nginx -p 0.0.0.0:{{ container_port }}:{{ http_port }}
      --add-host dockerhost:{{ docker_host_ip }} nginx)
