---
- hosts: "{{ target }}"
  remote_user: root
  roles:
    - ../roles/common
  tasks:

  - name: checkout latest node-server
    shell: cd {{ node_server_root_folder }} && sudo git checkout . && sudo git pull

  - name: build node-server image
    shell: sudo docker build -t {{ node_server_image }} {{ node_server_root_folder }}

  - name: delete node-server container
    shell: sudo docker rm -f {{ node_server_container }}
    ignore_errors: yes

  - name: run new node-server container
    shell: (sudo docker run -d --name node-server -p 0.0.0.0:{{ node_server_container_port }}:{{ node_server_container_port }}
      -e PORT="{{ node_server_container_port }}" {{ node_server_image }})
