---
- hosts: "{{ target }}"
  remote_user: root
  roles:
    - ../roles/common
    - ../roles/nginx
  tasks:

  - name: checkout latest nginx
    shell: cd {{ nginx_root_folder }} && sudo git pull && sudo git checkout .

  - name: edit nginx.conf config
    shell: "sudo sed -i -e 's%{{ item.key }}%{{ item.value }}%g' {{ nginx_root_folder }}/nginx.conf"
    with_dict: "{{ replace }}"

  - name: build nginx image
    shell: sudo docker build -t {{ nginx_image }} {{ nginx_root_folder }}

  - name: delete nginx container
    shell: sudo docker rm -f {{ nginx_container }}
    ignore_errors: yes

  - name: run new nginx container
    shell: (sudo docker run -d --name {{ nginx_container }} -p 0.0.0.0:{{ nginx_container_port }}:{{ http_port }}
      --add-host dockerhost:{{ docker_host_ip }} {{ nginx_image }})
