---
- hosts: "{{ target }}"
  remote_user: root
  roles:
    - ../roles/common
  tasks:

  - name: pull latest scrapy
    shell: cd {{ scrapy_root_folder }} && sudo git pull && sudo git checkout .

  - name: build scrapy image
    shell: sudo docker build -t {{ scrapy_image }} {{ scrapy_root_folder }}

  - name: delete scrapy container
    shell: sudo docker rm -f {{ scrapy_container  }}
    ignore_errors: yes

  - name: run new scrapy container
    shell: (sudo docker run -d --name {{ scrapy_container }}-{{ crawler }} --link {{ es_container }}:elasticsearch
      {{ scrapy_image }} crawl {{ crawler }})
