---
- hosts: "{{ target }}"
  remote_user: root
  roles:
    - ../roles/nginx
  tasks:

  - name: pull latest nginx
    shell: cd /etc/nginx && sudo git pull

  - name: edit nginx.conf config
    shell: echo "{{ item.key }} and {{ item.value }}" > /tmp/example.txt
    with_dict: "{{ replace }}"

  - name: build nginx image
    shell: sudo docker build -t "nginx" /etc/nginx

  - name: delete nginx container
    shell: sudo docker rm -f {{ container_name }}
    ignore_errors: yes

  - name: run new nginx container
    shell: (sudo docker run -d --name nginx -p 0.0.0.0:{{ container_port }}:{{ http_port }}
      --add-host dockerhost:{{ docker_host_ip }} nginx)
