---
- hosts: "{{ target }}"
  remote_user: root
  roles:
    - nginx
  tasks:
  - name: pull latest nginx
    shell: cd /etc/nginx && sudo git pull
  - name: build nginx image
    shell: sudo docker build -t "nginx" /etc/nginx
  - name: delete container
    shell: sudo docker kill {{ container_name }} && sudo docker rm {{ container_name }}
