---
- hosts: "{{ target }}"
  remote_user: root
  roles:
    - nginx
  tasks:
  - name: pull latest nginx
    shell: cd /etc/nginx && git pull
  - name: build nginx image
    shell: docker build -t "nginx" /etc/nginx
  - name: delete container
    shell: docker kill {{ container_name }} && docker rm {{ container_name }}
