---

include_vars:
  file: ../../common/vars/main.yml
  name: common_vars

http_port: 443
docker_host_name: dockerhost

replace:
  REPLACE_USER: nginx
  REPLACE_WORKER_PROCESSES: 2
  REPLACE_ERROR_LOG: /var/log/nginx/error.log warn
  REPLACE_PID: /var/run/nginx.pid
  REPLACE_WORKER_CONNECTIONS: 1024
  REPLACE_MAX_CLIENTS: 200

  REPLACE_HTTP_INCLUDE: /etc/nginx/mime.types
  REPLACE_HTTP_DEFAULT_TYPE: application/octet-stream
  REPLACE_HTTP_LOG_FORMAT: 'main \$remote_addr - \$remote_user [$time_local] \"\$request\"
                            \$status \$body_bytes_sent \"\$http_referer\"
                            \"\$http_user_agent\" \"\$http_x_forwarded_for\"'
  REPLACE_HTTP_ACCESS_LOG: /var/log/nginx/access.log main
  REPLACE_HTTP_SEND_FILE: "on"
  REPLACE_HTTP_TCP_NOPUSH: "on"
  REPLACE_HTTP_KEEPALIVE_TIMEOUT: 60
  REPLACE_HTTP_GZIP: "on"
  REPLACE_HTTP_PORT: 443

  REPLACE_KIBANA_ENDPOINT: /kibana
  REPLACE_KIBANA_PROXY: http://{{ docker_host_name }}:{{ common_vars['kibana_container_port'] }}

  REPLACE_NODE_SERVER_ENDPOINT: /
  REPLACE_NODE_SERVER_PROXY: http://dockerhost:8081

  REPLACE_CONFLUENCE_END_POINT: /confluence
  REPLACE_CONFLUENCE_PROXY: http://dockerhost:8090

  REPLACE_MYSQL_END_POINT: /maria
  REPLACE_MYSQL_PROXY: http://dockerhost:3306
