---
user: nginx
worker_processes: 2
error_log: /var/log/nginx/error.log warn
pid: /var/run/nginx.pid

worker_connections: 1024

http_port: 80
max_clients: 200

container_name: nginx
container_port: 3001
